#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 25

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_frame_opacity 0.3
bspc config focused_frame_opacity 0.3

bspc rule -a tint2 floating=on manage=off
bspc rule -a dendrite state=floating
