#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 25

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color '#444444'
bspc config active_border_color '#444444'
bspc config focused_border_color '#777777'

bspc rule -a polybar floating=on manage=off
bspc rule -a dendrite state=floating
